create table
  public.global_inventory (
    id bigint generated by default as identity,
    num_red_ml integer null,
    gold integer null,
    num_blue_ml integer null,
    num_green_ml integer null,
    total_potions integer null,
    constraint potion table_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.potion_table (
    id bigint generated by default as identity,
    sku text null,
    name text null,
    price integer null default 0,
    red integer null default 0,
    green integer null default 0,
    blue integer null default 0,
    dark integer null default 0,
    quantity integer null,
    constraint potion_table_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.carts (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    customer text null,
    constraint carts_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.cart_items (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    potion_id bigint null,
    quantity integer null,
    cart_id bigint null,
    constraint cart_item_pkey primary key (id),
    constraint cart_items_cart_id_fkey foreign key (cart_id) references carts (id),
    constraint cart_items_potion_id_fkey foreign key (potion_id) references potion_table (id)
  ) tablespace pg_default;
