create table
  public.global_inventory (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    num_red_potions integer null,
    num_red_ml integer null,
    gold integer null,
    num_blue_potions integer null,
    num_blue_ml integer null,
    num_green_potions integer null,
    num_green_ml integer null,
    constraint potion table_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.potion_table (
    id bigint generated by default as identity,
    sku text null,
    name text null,
    quantity integer null default 0,
    price integer null default 0,
    red integer null default 0,
    green integer null default 0,
    blue integer null default 0,
    dark integer null default 0,
    constraint potion_table_pkey primary key (id)
  ) tablespace pg_default;

