create table
  public.potion_table (
    id bigint generated by default as identity,
    sku text null,
    name text null,
    price integer null default 0,
    red integer null default 0,
    green integer null default 0,
    blue integer null default 0,
    dark integer null default 0,
    constraint potion_table_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.carts (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    customer text null,
    constraint carts_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.cart_items (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    potion_id bigint null,
    quantity integer null,
    cart_id bigint null,
    checkout boolean null default false,
    constraint cart_item_pkey primary key (id),
    constraint cart_items_cart_id_fkey foreign key (cart_id) references carts (id),
    constraint cart_items_potion_id_fkey foreign key (potion_id) references potion_table (id)
  ) tablespace pg_default;

create table
  public.gold_ledger (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    gold_change integer null default 0,
    transaction_id bigint null,
    constraint gold_ledger_pkey primary key (id),
    constraint gold_ledger_transaction_id_fkey foreign key (transaction_id) references transactions (id)
  ) tablespace pg_default;

create table
  public.ml_ledger (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    red_change integer null default 0,
    green_change integer null default 0,
    blue_change integer null default 0,
    dark_change integer null default 0,
    transaction_id bigint null,
    constraint ml_ledger_pkey primary key (id),
    constraint ml_ledger_transaction_id_fkey foreign key (transaction_id) references transactions (id)
  ) tablespace pg_default;

create table
  public.potion_ledger (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    potion_id bigint null,
    potion_change integer null default 0,
    transaction_id bigint null,
    cart_items_id bigint null,
    constraint potion_ledger_pkey primary key (id),
    constraint potion_ledger_cart_items_id_fkey foreign key (cart_items_id) references cart_items (id),
    constraint potion_ledger_potion_id_fkey foreign key (potion_id) references potion_table (id),
    constraint potion_ledger_transaction_id_fkey foreign key (transaction_id) references transactions (id)
  ) tablespace pg_default;

create table
  public.transactions (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    description text null,
    constraint transactions_pkey primary key (id)
  ) tablespace pg_default;